# Generated by Django 4.0.6 on 2022-08-01 10:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SlideModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50)),
                ('body', models.CharField(blank=True, max_length=200)),
                ('img1', models.ImageField(upload_to='slide/')),
                ('img2', models.ImageField(upload_to='slide/')),
                ('img3', models.ImageField(blank=True, upload_to='slide/')),
                ('img4', models.ImageField(blank=True, upload_to='slide/')),
                ('img5', models.ImageField(blank=True, upload_to='slide/')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
