# Generated by Django 4.0.6 on 2022-08-02 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sliyds', '0002_rename_body_slidemodel_body1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slidemodel',
            name='body1',
            field=models.CharField(blank=True, default='Этот слайд создан только для преданных фанатов аниме Наруто !', max_length=200),
        ),
        migrations.AlterField(
            model_name='slidemodel',
            name='body2',
            field=models.CharField(blank=True, default='Этот слайд создан только для преданных фанатов аниме Наруто !', max_length=200),
        ),
        migrations.AlterField(
            model_name='slidemodel',
            name='body3',
            field=models.CharField(blank=True, default='Этот слайд создан только для преданных фанатов аниме Наруто !', max_length=200),
        ),
        migrations.AlterField(
            model_name='slidemodel',
            name='body4',
            field=models.CharField(blank=True, default='Этот слайд создан только для преданных фанатов аниме Наруто !', max_length=200),
        ),
        migrations.AlterField(
            model_name='slidemodel',
            name='body5',
            field=models.CharField(blank=True, default='Этот слайд создан только для преданных фанатов аниме Наруто !', max_length=200),
        ),
        migrations.AlterField(
            model_name='slidemodel',
            name='name1',
            field=models.CharField(blank=True, default='AnimeFan', max_length=50),
        ),
        migrations.AlterField(
            model_name='slidemodel',
            name='name2',
            field=models.CharField(blank=True, default='AnimeFan', max_length=50),
        ),
        migrations.AlterField(
            model_name='slidemodel',
            name='name3',
            field=models.CharField(blank=True, default='AnimeFan', max_length=50),
        ),
        migrations.AlterField(
            model_name='slidemodel',
            name='name4',
            field=models.CharField(blank=True, default='AnimeFan', max_length=50),
        ),
        migrations.AlterField(
            model_name='slidemodel',
            name='name5',
            field=models.CharField(blank=True, default='AnimeFan', max_length=50),
        ),
    ]
