# Generated by Django 4.0.6 on 2022-08-02 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sliyds', '0003_alter_slidemodel_body1_alter_slidemodel_body2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slidemodel',
            name='body1',
            field=models.CharField(default='Этот слайд создан только для преданных фанатов аниме Наруто !', max_length=200),
        ),
        migrations.AlterField(
            model_name='slidemodel',
            name='body2',
            field=models.CharField(default='Этот слайд создан только для преданных фанатов аниме Наруто !', max_length=200),
        ),
        migrations.AlterField(
            model_name='slidemodel',
            name='name1',
            field=models.CharField(default='AnimeFan', max_length=50),
        ),
        migrations.AlterField(
            model_name='slidemodel',
            name='name2',
            field=models.CharField(default='AnimeFan', max_length=50),
        ),
    ]
