# Generated by Django 4.0.6 on 2022-08-03 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sliyds', '0004_alter_slidemodel_body1_alter_slidemodel_body2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slidemodel',
            name='body3',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='slidemodel',
            name='body4',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='slidemodel',
            name='body5',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='slidemodel',
            name='name3',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='slidemodel',
            name='name5',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
