# Generated by Django 4.0.6 on 2022-07-20 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('accounts', '0003_rename_customuser_fanatuser'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FanatUser',
            new_name='CustomUser',
        ),
    ]
